import ai_os.core.macro_helpers as ah
import sys 
import os

## Generates a test file, asks for approval
# Then will generate code to solve the test
# Then will run the test, and check if it passes
# if success, it will commit the changes
# If fail it wil looop and try again

test_prompt_template = """
Generate a test file for the following goal:
{test_goal}

The test should test the test_goal and import a file and functions to test

It should run tests and return a 0 exit code on success or non-zero on failure.
Keep the file simple 

The test file should be in the file: tests/test_{test_goal_snake}.py

IMPORTANT: The test will be run from the examples directory, so make sure imports work correctly.
Add this at the top of the test file to ensure imports work:
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
"""

patch_prompt_template = """
Given the user goal and test file contents, write the code to pass the test.
Goal:
{test_goal}

Test file:
{test_file_contents}

"""




def main(ctx, **kwargs):
    goal = kwargs.get("test_goal")
    if not goal:
        ah.log("Error: test_goal argument is required.")
        ah.log("Usage: /macro examples/tdd_macro.py test_goal='...'")
        return

    # Convert goal to snake_case for filename
    import re
    test_goal_snake = re.sub(r'[^a-zA-Z0-9]+', '_', goal).strip('_').lower()
    
    test_file = None
    while True:
        test_prompt = test_prompt_template.format(test_goal=goal, test_goal_snake=test_goal_snake)
        patch = ah.patch(test_prompt)
        
        # Check if patch was applied successfully
        if not patch or not patch.get("applied"):
            ah.log(f"Patch was not applied: {patch}")
            if not ah.approve("Retry patch?"):
                ah.log("User cancelled patch retry.")
                return
            continue
            
        files = patch.get("files") if patch else None
        if not files or len(files) == 0:
            ah.log("No files were generated by the patch. Retrying...")
            continue
            
        test_file = files[0]
        
        # Verify the file actually exists
        import os
        if not os.path.exists(test_file.path):
            ah.log(f"Error: Test file {test_file.path} was not created on disk.")
            if not ah.approve("Retry patch?"):
                ah.log("User cancelled patch retry.")
                return
            continue
            
        approval = ah.approve(f"Is test file {test_file.path} ok?")
        if approval:
            break
        else:
            ah.log(f"Test file {test_file.path} rejected. Retrying...")
        
    test_command = f"pytest {test_file.path}"

    while True:
        ah.log(f"Running test: {test_command}")
        patch_prompt = patch_prompt_template.format(test_goal=goal, test_file_contents=test_file.contents)
        patch = ah.patch(patch_prompt, user_approval=True)
        
        # Check if implementation patch was applied
        if not patch or not patch.get("applied"):
            ah.log(f"Implementation patch was not applied: {patch}")
            error_msg = patch.get("error", "Unknown error") if patch else "No patch returned"
            ah.log(f"Error details: {error_msg}")
            
            # Check if file already exists
            import os
            impl_path = "src/math_functions.py"  # Adjust based on your needs
            if os.path.exists(impl_path):
                ah.log(f"Note: Implementation file already exists at {impl_path}")
                # Try to run tests anyway
                ah.log("Attempting to run tests with existing implementation...")
            else:
                if not ah.approve("Retry implementation?"):
                    ah.log("User cancelled implementation retry.")
                    return
                continue
            
        exit_code = ah.shell(test_command, capture=False)
        if exit_code == 0:
            ah.log("[bold green]Tests passed![/bold green]")
            break
        else:
            ah.log("[bold yellow]Tests failed.[/bold yellow]")
            if not ah.approve("Retry with another implementation?"):
                ah.log("User cancelled implementation retry.")
                return
            ah.log(f"Retrying test: {test_command}")
