import ai_os.core.macro_helpers as ah
import sys 
import os

## Generates a test file, asks for approval
# Then will generate code to solve the test
# Then will run the test, and check if it passes
# if success, it will commit the changes
# If fail it wil looop and try again

test_prompt_template = """
Generate a test file for the following goal:
{test_goal}

The test should test the test_goal and import a file and functions to test

It should run tests and return a 0 exit code on success or non-zero on failure.
Keep the file simple 


The test file should be in the file:

"""

patch_prompt_template = """
Given the user goal and test file contents, write the code to pass the test.
Goal:
{test_goal}

Test file:
{test_file_contents}

"""




def main(ctx, **kwargs):
    goal = kwargs.get("test_goal")
    if not goal:
        ah.log("Error: test_goal argument is required.")
        ah.log("Usage: /macro examples/tdd_macro.py test_goal='...'")
        return

    while True:
        test_prompt = test_prompt_template.format(test_goal=goal)
        patch = ah.patch(test_prompt)
        files = patch.get("files") if patch else None
        if not files or len(files) == 0:
            ah.log("No files were generated by the patch. Retrying...")
            continue
        test_file = files[0]
        approval = ah.approve(f"Is test file {test_file.path} ok?")
        if approval:
            break
        else:
            ah.log(f"Test file {test_file} rejected. Retrying...")
        
    test_command = f"pytest {test_file}"

    while True:
        ah.log(f"Running test: {test_command}")
        patch_prompt = patch_prompt_template.format(test_goal=goal, test_file_contents=test_file.contents)
        patch = ah.patch(patch_prompt, commit=True)
        # shell_result = ah.shell(test_command, capture=False)
        # Use python utils to call instead
        # Shell out os or exec or sub
        import subprocess
        shell_result = subprocess.run(test_command, capture_output=True, text=True)
        exit_code = shell_result.returncode
        if exit_code == 0:
            ah.log("[bold green]Tests passed![/bold green]")
            break
        else:
            ah.log("[bold yellow]Tests failed.[/bold yellow]")
            ah.log(f"Retrying test: {test_command}")
